# vtc_chatbot.py
# VTC AI Trainer Matching Chatbot
#
# Uses Groq (free LLM) for conversation, sentence-transformers for semantic matching,
# trainer_profiles_full.csv for all 11 factor data, and explainability.py for explanations.
#
# Setup:
#   pip install groq
#   Get a free API key at https://console.groq.com
#
# Run: streamlit run vtc_chatbot.py

import json
import numpy as np
import pandas as pd
import streamlit as st
from datetime import datetime
from groq import Groq
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from explainability import explain_match

PROFILES_PATH = "trainer_profiles_full.csv"
LLM_MODEL     = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are the Voltage Training Club (VTC) AI Trainer Matching Assistant.
Your job is to help clients find the right personal trainer through friendly conversation.

When a client tells you what they are looking for, use the search_trainers tool to find matches.
Never make up trainer names - always call the tool first.

After getting results, present the top trainers warmly and conversationally.
For each trainer you MUST use the 'explanation' field from the results as the reason why they are a good fit.
Do not make up your own reasons - the explanation is generated by our AI explainability system.
Mention the match score for each trainer.
Keep responses concise and encouraging.

If the client wants to refine their search, call the tool again with updated preferences.
If they ask general fitness questions, answer helpfully."""

TOOLS = [{
    "type": "function",
    "function": {
        "name": "search_trainers",
        "description": "Find the best matching trainers for a client. Call this whenever a client describes what they are looking for.",
        "parameters": {
            "type": "object",
            "properties": {
                "goals"  : {"type": "string", "description": "Fitness goals, e.g. weight loss, muscle gain, marathon training"},
                "style"  : {"type": "string", "description": "Preferred training style, e.g. HIIT, strength training, yoga"},
                "persona": {"type": "string", "description": "Preferred trainer personality, e.g. motivating, calm, energetic"},
            },
            "required": ["goals"],
        },
    },
}]


@st.cache_resource
def load_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

@st.cache_data
def load_profiles():
    return pd.read_csv(PROFILES_PATH)

@st.cache_resource
def encode_trainers(_profiles):
    mdl = load_model()
    return (
        mdl.encode(_profiles["goal_tags"].fillna("").tolist()),
        mdl.encode(_profiles["styles_offered"].fillna("").tolist()),
        mdl.encode(_profiles["personality_traits"].fillna("").tolist()),
        mdl.encode(_profiles["bio"].fillna("").tolist()),
    )


# score computation from raw trainer profile data

def score_recency(last_updated_str):
    try:
        last = datetime.strptime(str(last_updated_str), "%Y-%m-%d")
        days = (datetime(2026, 6, 6) - last).days
        if days <= 30:  return 1.00
        if days <= 90:  return 0.80
        if days <= 180: return 0.60
        if days <= 365: return 0.40
        return 0.20
    except:
        return 0.50

def score_experience(years):
    y = int(years) if years else 0
    if y >= 10: return 0.95
    if y >= 8:  return 0.85
    if y >= 5:  return 0.70
    if y >= 3:  return 0.55
    if y >= 1:  return 0.40
    return 0.20

def score_qualifications(certs):
    c = str(certs)
    if "ACE" in c and "CrossFit" in c: return 0.90
    if "ACE" in c or "CrossFit Level 2" in c: return 0.75
    if "NASM CPT" in c: return 0.60
    return 0.40

def score_education(edu):
    e = str(edu)
    if "Bachelor" in e or "Master" in e: return 0.85
    if "Diploma" in e: return 0.65
    return 0.45

def score_availability(avail):
    a = str(avail).lower()
    if "mon-sat" in a or "daily" in a: return 0.90
    if "mon-fri" in a: return 0.70
    return 0.50


def search_trainers(goals: str, style: str = "", persona: str = "") -> dict:
    """
    Full matching pipeline using trainer_profiles_full.csv.
    - Semantic matching for goal, style, persona scores
    - Computed directly from raw trainer data for recency, experience, qualifications, education, availability
    - Gender, age, location default to neutral (user did not provide these)
    """
    mdl      = load_model()
    profiles = load_profiles()
    t_goals, t_styles, t_personas, t_bios = encode_trainers(profiles)

    g_emb = mdl.encode([goals])
    s_emb = mdl.encode([style or ""])
    p_emb = mdl.encode([persona or ""])

    gs = np.clip(cosine_similarity(g_emb, t_goals)[0], 0, 1)
    ss = np.clip(cosine_similarity(s_emb, t_styles)[0], 0, 1)
    ps = np.clip(
        0.7 * cosine_similarity(p_emb, t_personas)[0] +
        0.3 * cosine_similarity(p_emb, t_bios)[0], 0, 1
    )
    fs = (1.5 * gs + 1.5 * ss + 0.7 * ps) / (1.5 + 1.5 + 0.7)

    top3    = np.argsort(fs)[::-1][:3]
    results = []

    for rank, idx in enumerate(top3, 1):
        t = profiles.iloc[idx]

        profile = {
            "trainer_id"        : str(t["trainer_id"]),
            "goal_tags"         : str(t.get("goal_tags", "")),
            "styles_offered"    : str(t.get("styles_offered", "")),
            "personality_traits": str(t.get("personality_traits", "")),
            "bio"               : str(t.get("bio", "")),
        }

        # 3 scores from semantic matching
        # 5 scores computed from real trainer profile data
        # 3 scores defaulted to neutral (gender, age, location need user input)
        scores = {
            "goal_score"          : round(float(gs[idx]), 4),
            "style_score"         : round(float(ss[idx]), 4),
            "persona_score"       : round(float(ps[idx]), 4),
            "gender_score"        : 0.70,   # neutral - user did not specify preference
            "availability_score"  : round(score_availability(t.get("availability", "")), 4),
            "age_score"           : 0.70,   # neutral - user did not provide age
            "qualification_score" : round(score_qualifications(t.get("certifications", "")), 4),
            "education_score"     : round(score_education(t.get("education", "")), 4),
            "location_score"      : 0.70,   # neutral - user did not provide location
            "recency_score"       : round(score_recency(t.get("last_updated", "")), 4),
            "experience_score"    : round(score_experience(t.get("years_experience", 0)), 4),
            "final_score"         : round(float(fs[idx]), 4),
        }

        explanation = explain_match(profile, scores)

        results.append({
            "rank"           : rank,
            "trainer_id"     : profile["trainer_id"],
            "score"          : scores["final_score"],
            "location"       : str(t.get("location", "")),
            "experience"     : f"{t.get('years_experience', '?')} years",
            "availability"   : str(t.get("availability", "")),
            "explanation"    : explanation,
        })

    return {"matches": results, "total_trainers_searched": len(profiles)}


def call_llm(messages: list, api_key: str) -> tuple:
    client   = Groq(api_key=api_key)
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=messages,
        tools=TOOLS,
        tool_choice="auto",
        max_tokens=1024,
    )
    msg = response.choices[0].message

    if msg.tool_calls:
        tool_call = msg.tool_calls[0]
        args      = json.loads(tool_call.function.arguments)
        result    = search_trainers(**args)

        messages.append({
            "role"      : "assistant",
            "content"   : msg.content or "",
            "tool_calls": [{
                "id"      : tool_call.id,
                "type"    : "function",
                "function": {"name": tool_call.function.name, "arguments": tool_call.function.arguments},
            }],
        })
        messages.append({
            "role"        : "tool",
            "tool_call_id": tool_call.id,
            "content"     : json.dumps(result),
        })

        final = client.chat.completions.create(
            model=LLM_MODEL,
            messages=messages,
            max_tokens=1024,
        )
        reply = final.choices[0].message.content
    else:
        reply = msg.content

    messages.append({"role": "assistant", "content": reply})
    return reply, messages


# page setup
st.set_page_config(page_title="VTC Trainer Matching Chatbot", layout="centered")
st.markdown("""
<style>
.stApp { background-color: #f7f3ff; }
</style>
""", unsafe_allow_html=True)

st.title("Voltage Training Club")
st.subheader("AI Trainer Matching Chatbot")
st.caption("Tell me what you are looking for and I will find you the best trainer.")

st.sidebar.markdown("### Setup")
api_key = st.sidebar.text_input(
    "Groq API Key",
    type="password",
    placeholder="Get a free key at console.groq.com",
    help="Your key is never stored. Get a free one at https://console.groq.com"
)
st.sidebar.markdown("---")
st.sidebar.markdown("**How it works:**")
st.sidebar.markdown(
    "1. Tell the chatbot your fitness goals\n"
    "2. Semantic AI matches you to trainers across 11 factors\n"
    "3. Each recommendation comes with a plain English explanation\n"
)

if "messages" not in st.session_state:
    st.session_state.messages = []
if "llm_history" not in st.session_state:
    st.session_state.llm_history = [{"role": "system", "content": SYSTEM_PROMPT}]

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if prompt := st.chat_input("Tell me your fitness goals..."):
    if not api_key:
        st.warning("Please enter your Groq API key in the sidebar. Get a free one at console.groq.com")
        st.stop()

    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    st.session_state.llm_history.append({"role": "user", "content": prompt})

    with st.chat_message("assistant"):
        with st.spinner("Finding your best trainers..."):
            try:
                reply, updated = call_llm(st.session_state.llm_history, api_key)
                st.session_state.llm_history = updated
                st.markdown(reply)
                st.session_state.messages.append({"role": "assistant", "content": reply})
            except Exception as e:
                err = f"Something went wrong: {e}"
                st.error(err)
                st.session_state.messages.append({"role": "assistant", "content": err})
